### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Prabesh-Shrestha** [Prabesh-Shrestha/rusty-server#2]
fill up the readme.md file, make it as attractive as you can. 
maybe add images of the example project

**Comment by najeebkp** [comment]
hi @Prabesh-Shrestha  please assign this to me

**Comment by Prabesh-Shrestha** [comment]
happy to @najeebkp, work on this and inform us if you have any problem 🚀

**Comment by najeebkp** [comment]
@Prabesh-Shrestha can you please share one screenshot of the project so that i can include in readme?

**Comment by Prabesh-Shrestha** [comment]
![image](https://user-images.githubusercontent.com/65012735/196861318-6b356c03-251e-4615-8e17-cc54aa2fd85f.png)

**Comment by najeebkp** [comment]
Thanks @Prabesh-Shrestha

**Comment by Prabesh-Shrestha** [comment]
thank you @najeebkp for your contribution, you can check out other issues too, have a nice day
